parameters:
  locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MeetMatt\Colla\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  MeetMatt\Colla\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  mhujer.jms_serializer.uuid.uuid_serializer_handler:
    class: Mhujer\JmsSerializer\Uuid\UuidSerializerHandler
    tags:
      - { name: jms_serializer.subscribing_handler }

  meet_matt.colla.event.jwt_created_listener:
    class: MeetMatt\Colla\EventListener\JWTCreatedListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }