security:

  encoders:
    MeetMatt\Colla\Entity\User:
      algorithm: bcrypt

  providers:
    jwt:
      lexik_jwt:
        class: MeetMatt\Colla\Entity\User
    colla.user_provider:
      entity:
        class: MeetMatt\Colla\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/api/dev/(_(profiler|wdt))/
      security: false

    register:
      pattern: ^/api/v1/user/register
      stateless: true
      anonymous: true

    login:
      pattern: ^/api/v1/auth/login
      stateless: true
      anonymous: true
      provider: colla.user_provider
      json_login:
        check_path: /api/v1/auth/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    api:
      pattern: ^/api
      stateless: true
      anonymous: false
      provider: jwt
      guard:
        authenticators:
        - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
  - { path: ^/api/v1/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/api/v1/auth/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/api,                  roles: IS_AUTHENTICATED_FULLY       }
