security:

  encoders:
    Symfony\Componen\Security\Core\User\User:
      algorithm: argon2i
      memory_cost: 16384
      time_cost:   2
      threads:     1

  providers:
    jwt:
      lexik_jwt:
        class: MeetMatt\Colla\Entity\User

  firewalls:
    dev:
      pattern: ^/api/dev/(_(profiler|wdt))/
      security: false

    login:
      pattern: ^/api/v1/auth/login
      stateless: true
      anonymous: true
      json_login:
        check_path: /api/v1/auth/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    api:
      pattern: ^/api
      stateless: true
      provider: jwt
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/api/v1/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,               roles: IS_AUTHENTICATED_FULLY }
